enum DisplayedPage { HOME, PRODUCTS, ORDERS, USERS, BRANDS, CATEGORIES,ONLINEDEPOSITE, FOLLOWREPORT, DOWNLOADACCOUNTINGSTANDARDS, FINANCIELMANAGMENT, COURRIERS, EDOC }
//enum DisplayedPageCdc { ONLINEDEPOSITE, FOLLOWREPORT, DOWNLOADACCOUNTINGSTANDARDS, FINANCIELMANAGMENT, COURRIERS, EDOC }
